### ISSUE TITLE
Network BGP errors

### ISSUE THREAD

**Issue by carlosfparada** [redhat-cop/network.bgp#20]
I am trying to run the validated content in the collection network.bgp. However, it did not work properly for any of the examples provided in the module documentation. I am running it from the controller.

Plays:
- name: Gather Facts
  hosts: ios
  gather_facts: false
  tasks:
  - name: BGP Manager
    ansible.builtin.include_role:
      name: network.bgp.run
    vars:
      actions:
        - name: gather

- name: Perform health checks
  hosts: ios
  gather_facts: false
  vars:
  tasks:
  - name: BGP Manager
    ansible.builtin.include_role:
      name: network.bgp.run
    vars:
      actions:
        - name: health_check
          vars:
            details: True
            checks:
              - name: all_neighbors_up
              - name: all_neighbors_down
              - name: min_neighbors_up
                min_count: 1

Logs (gather action):
TASK [Invoke gather function] **************************************************
task path: /usr/share/ansible/collections/ansible_collections/network/bgp/roles/run/tasks/includes/gather.yaml:2
ERROR! the role ‘../../base/roles/resource_manager’ was not found in network.bgp:ansible.builtin:/runner/project/roles:/runner/requirements_roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project
The error appears to be in ‘/usr/share/ansible/collections/ansible_collections/network/bgp/roles/run/tasks/includes/gather.yaml’: line 4, column 11, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
 ansible.builtin.include_role:
 name: ../../base/roles/resource_manager
 ^ here

Logs (health_check action):
TASK [network.bgp.run : Include tasks] *****************************************
task path: /usr/share/ansible/collections/ansible_collections/network/bgp/roles/run/tasks/includes/health_check.yaml:2
fatal: [ios-sw1]: FAILED! => {
    "msg": "list object has no element 2. list object has no element 2"
}
fatal: [ios-rt2]: FAILED! => {
    "msg": "list object has no element 2. list object has no element 2"
}
fatal: [ios-rt1]: FAILED! => {
    "msg": "list object has no element 2. list object has no element 2"
}

**Comment by rohitthakur2590** [comment]
@carlosfparada  Thanks for reporting this. Could you please try with release 2.0.0.
and also the health_checks, gather and  other  tasks expects `ansible.network.os` like mentioned here  
https://github.com/rohitthakur2590/network_validated_content_demo/blob/main/playbooks/bgp/health_check.yaml

https://github.com/rohitthakur2590/network_validated_content_demo/blob/4c390456765108402bb85c4dee95710b7aaeeee9/playbooks/bgp/gather.yaml#L9
