### ISSUE TITLE
Variable `inventory_directory` not used with `persist` or `deploy` action

### ISSUE THREAD

**Issue by NilashishC** [redhat-cop/network.bgp#29]
The `inventory_directory` variable isn't used for any of these actions, even though README examples show this as a configurable action. It always uses `host_vars/{{ inventory_hostname }}` from the current working directory.

This should probably be a ticket in  `network.base` but since the READMEs in the resource specific validated contents mention this option, I'm opening it here.

**Comment by rohitthakur2590** [comment]
resolved by:  https://github.com/redhat-cop/network.base/pull/42
